version: '3.9'

services:
  customer-service:
    build:
      context: ./../customer-service
      dockerfile: ./../customer-service/customer-service.dockerfile
    image: ${CUSTOMER_SERVICE_IMAGE_NAME}
    container_name: ${CUSTOMER_SERVICE_CONTAINER_NAME}
    restart: always
    depends_on:
      customer-db:
        condition: service_healthy  # Wait for DB to be ready
    ports:
      - "${CUSTOMER_SERVICE_PORT}:${CUSTOMER_SERVICE_PORT}"
    env_file:
      - .env  # Load environment variables

  customer-db:
    image: postgres:15
    container_name: customer-db
    restart: always
    environment:
      POSTGRES_USER: ${CUSTOMER_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${CUSTOMER_POSTGRES_DB_NAME}
    ports:
      - "${CUSTOMER_POSTGRES_DB_PORT}:5432"
    healthcheck:  # Ensure PostgreSQL is ready before starting customer-service
      test: ["CMD", "pg_isready", "-U", "${CUSTOMER_POSTGRES_DB_USER}", "-d", "${CUSTOMER_POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - customer_db_data:/var/lib/postgresql/data

volumes:
  customer_db_data:
