version: '3.9'

services:
  customer-service:
    build:
      context: ./../customer-service
      dockerfile: ./../customer-service/customer-service.dockerfile
    image: ${CUSTOMER_SERVICE_IMAGE_NAME}
    container_name: ${CUSTOMER_SERVICE_CONTAINER_NAME}
    restart: always
    depends_on:
      - customer-db
    ports:
      - "${CUSTOMER_SERVICE_PORT}:${CUSTOMER_SERVICE_PORT}"
    env_file:
      - .env  # Make sure environment variables are loaded

  customer-db:
    image: postgres:15
    container_name: customer-db
    restart: always
    environment:
      POSTGRES_USER: ${CUSTOMER_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${CUSTOMER_POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${CUSTOMER_POSTGRES_DB_NAME}
    ports:
      - "${CUSTOMER_POSTGRES_DB_PORT}:${CUSTOMER_POSTGRES_DB_PORT}"
    volumes:
      - customer_db_data:/var/lib/postgresql/data

volumes:
  customer_db_data:
